const black = {
    player: {
        type: human,
        moveCount: 0,
        playTime: 0,

    },
    piece1: {
        pc1: 12,
        pc2: 13,

    },
    piece2: {
        pc1: 12,
        pc2: 13,

    },
    piece3: {
        pc1: 12,
        pc2: 13,

    },
    piece4: {
        pc1: 12,
        pc2: 13,

    },
    piece5: {
        pc1: 12,
        pc2: 13,

    },
    piece6: {
        pc1: 12,
        pc2: 13,

    }
}

const white = {
    piece1: {
        pc1: 12,
        pc2: 13,

    },
    piece2: {
        pc1: 12,
        pc2: 13,

    },
    piece3: {
        pc1: 12,
        pc2: 13,

    },
    piece4: {
        pc1: 12,
        pc2: 13,

    },
    piece5: {
        pc1: 12,
        pc2: 13,

    },
    piece6: {
        pc1: 12,
        pc2: 13,

    }
}
const cases = {
    truc: {
        pieceName: 'rook_03',
        pieceColor: 'black',
        isAlive: 1,
        positionX: 1,
        positionY: 8,
        caseColor: 'white',
        pawn_spec: 0,
    },
    truc: {
        pieceName: 'knight_03',
        pieceColor: 'black',
        isAlive: 1,
        positionX: 2,
        positionY: 8,
        caseColor: 'black',
        pawn_spec: 0,
    },
    truc: {
        pieceName: 'bishop_03',
        pieceColor: 'black',
        isAlive: 1,
        positionX: 3,
        positionY: 8,
        caseColor: 'white',
        pawn_spec: 0,
    },
    truc: {
        pieceName: 'queen_02',
        pieceColor: 'black',
        isAlive: 1,
        positionX: 4,
        positionY: 8,
        caseColor: 'black',
        pawn_spec: 0,
    },
    truc: {
        pieceName: 'king_02',
        pieceColor: 'black',
        isAlive: 1,
        positionX: 5,
        positionY: 8,
        caseColor: 'white',
        pawn_spec: 0,
    },
    truc: {
        pieceName: 'bishop_04',
        pieceColor: 'black',
        isAlive: 1,
        positionX: 6,
        positionY: 8,
        caseColor: 'black',
        pawn_spec: 0,
    },
    truc: {
        pieceName: 'knight_04',
        pieceColor: 'black',
        isAlive: 1,
        positionX: 7,
        positionY: 8,
        caseColor: 'white',
        pawn_spec: 0,
    },
    truc: {
        pieceName: 'rook_04',
        pieceColor: 'black',
        isAlive: 1,
        positionX: 8,
        positionY: 8,
        caseColor: 'black',
        pawn_spec: 0,
    },
    truc: {
        pieceName: 'pawn_09',
        pieceColor: 'black',
        isAlive: 1,
        positionX: 1,
        positionY: 7,
        caseColor: 'black',
        pawn_spec: 0,
    },
    truc: {
        pieceName: 'pawn_10',
        pieceColor: 'black',
        isAlive: 1,
        positionX: 2,
        positionY: 7,
        caseColor: 'white',
        pawn_spec: 0,
    },
    truc: {
        pieceName: 'pawn_11',
        pieceColor: 'black',
        isAlive: 1,
        positionX: 3,
        positionY: 7,
        caseColor: 'black',
        pawn_spec: 0,
    },
    truc: {
        pieceName: 'pawn_12',
        pieceColor: 'black',
        isAlive: 1,
        positionX: 4,
        positionY: 7,
        caseColor: 'white',
        pawn_spec: 0,
    },
    truc: {
        pieceName: 'pawn_13',
        pieceColor: 'black',
        isAlive: 1,
        positionX: 5,
        positionY: 7,
        caseColor: 'black',
        pawn_spec: 0,
    },
    truc: {
        pieceName: 'pawn_14',
        pieceColor: 'black',
        isAlive: 1,
        positionX: 6,
        positionY: 7,
        caseColor: 'white',
        pawn_spec: 0,
    },
    truc: {
        pieceName: 'pawn_15',
        pieceColor: 'black',
        isAlive: 1,
        positionX: 7,
        positionY: 7,
        caseColor: 'black',
        pawn_spec: 0,
    },
    truc: {
        pieceName: 'pawn_16',
        pieceColor: 'black',
        isAlive: 1,
        positionX: 8,
        positionY: 7,
        caseColor: 'white',
        pawn_spec: 0,
    },
    truc: {
        pieceName: 'none',
        pieceColor: 'none',
        isAlive: 0,
        positionX: 1,
        positionY: 6,
        caseColor: 'white',
        pawn_spec: 0,
    },
    truc: {
        pieceName: 'none',
        pieceColor: 'none',
        isAlive: 0,
        positionX: 2,
        positionY: 6,
        caseColor: 'black',
        pawn_spec: 0,
    },
    truc: {
        pieceName: 'none',
        pieceColor: 'none',
        isAlive: 0,
        positionX: 3,
        positionY: 6,
        caseColor: 'white',
        pawn_spec: 0,
    },
    truc: {
        pieceName: 'none',
        pieceColor: 'none',
        isAlive: 0,
        positionX: 4,
        positionY: 6,
        caseColor: 'black',
        pawn_spec: 0,
    },
    truc: {
        pieceName: 'none',
        pieceColor: 'none',
        isAlive: 0,
        positionX: 5,
        positionY: 6,
        caseColor: 'white',
        pawn_spec: 0,
    },
    truc: {
        pieceName: 'none',
        pieceColor: 'none',
        isAlive: 0,
        positionX: 6,
        positionY: 6,
        caseColor: 'black',
        pawn_spec: 0,
    },
    truc: {
        pieceName: 'none',
        pieceColor: 'none',
        isAlive: 0,
        positionX: 7,
        positionY: 6,
        caseColor: 'white',
        pawn_spec: 0,
    },
    truc: {
        pieceName: 'none',
        pieceColor: 'none',
        isAlive: 0,
        positionX: 8,
        positionY: 6,
        caseColor: 'black',
        pawn_spec: 0,
    },
    truc: {
        pieceName: 'none',
        pieceColor: 'none',
        isAlive: 0,
        positionX: 1,
        positionY: 5,
        caseColor: 'black',
        pawn_spec: 0,
    },
    truc: {
        pieceName: 'none',
        pieceColor: 'none',
        isAlive: 0,
        positionX: 2,
        positionY: 5,
        caseColor: 'white',
        pawn_spec: 0,
    },
    truc: {
        pieceName: 'none',
        pieceColor: 'none',
        isAlive: 0,
        positionX: 3,
        positionY: 5,
        caseColor: 'black',
        pawn_spec: 0,
    },
    truc: {
        pieceName: 'none',
        pieceColor: 'none',
        isAlive: 0,
        positionX: 4,
        positionY: 5,
        caseColor: 'white',
        pawn_spec: 0,
    },
    truc: {
        pieceName: 'none',
        pieceColor: 'none',
        isAlive: 0,
        positionX: 5,
        positionY: 5,
        caseColor: 'black',
        pawn_spec: 0,
    },
    truc: {
        pieceName: 'none',
        pieceColor: 'none',
        isAlive: 0,
        positionX: 6,
        positionY: 5,
        caseColor: 'white',
        pawn_spec: 0,
    },
    truc: {
        pieceName: 'none',
        pieceColor: 'none',
        isAlive: 0,
        positionX: 7,
        positionY: 5,
        caseColor: 'black',
        pawn_spec: 0,
    },
    truc: {
        pieceName: 'none',
        pieceColor: 'none',
        isAlive: 0,
        positionX: 8,
        positionY: 5,
        caseColor: 'white',
        pawn_spec: 0,
    },
    truc: {
        pieceName: 'none',
        pieceColor: 'none',
        isAlive: 0,
        positionX: 1,
        positionY: 4,
        caseColor: 'white',
        pawn_spec: 0,
    },
    truc: {
        pieceName: 'none',
        pieceColor: 'none',
        isAlive: 0,
        positionX: 2,
        positionY: 4,
        caseColor: 'black',
        pawn_spec: 0,
    },
    truc: {
        pieceName: 'none',
        pieceColor: 'none',
        isAlive: 0,
        positionX: 3,
        positionY: 4,
        caseColor: 'white',
        pawn_spec: 0,
    },
    truc: {
        pieceName: 'none',
        pieceColor: 'none',
        isAlive: 0,
        positionX: 4,
        positionY: 4,
        caseColor: 'black',
        pawn_spec: 0,
    },
    truc: {
        pieceName: 'none',
        pieceColor: 'none',
        isAlive: 0,
        positionX: 5,
        positionY: 4,
        caseColor: 'white',
        pawn_spec: 0,
    },
    truc: {
        pieceName: 'none',
        pieceColor: 'none',
        isAlive: 0,
        positionX: 6,
        positionY: 4,
        caseColor: 'black',
        pawn_spec: 0,
    },
    truc: {
        pieceName: 'none',
        pieceColor: 'none',
        isAlive: 0,
        positionX: 7,
        positionY: 4,
        caseColor: 'white',
        pawn_spec: 0,
    },
    truc: {
        pieceName: 'none',
        pieceColor: 'none',
        isAlive: 0,
        positionX: 8,
        positionY: 4,
        caseColor: 'black',
        pawn_spec: 0,
    },
    truc: {
        pieceName: 'none',
        pieceColor: 'none',
        isAlive: 0,
        positionX: 1,
        positionY: 3,
        caseColor: 'black',
        pawn_spec: 0,
    },
    truc: {
        pieceName: 'none',
        pieceColor: 'none',
        isAlive: 0,
        positionX: 2,
        positionY: 3,
        caseColor: 'white',
        pawn_spec: 0,
    },
    truc: {
        pieceName: 'none',
        pieceColor: 'none',
        isAlive: 0,
        positionX: 3,
        positionY: 3,
        caseColor: 'black',
        pawn_spec: 0,
    },
    truc: {
        pieceName: 'none',
        pieceColor: 'none',
        isAlive: 0,
        positionX: 4,
        positionY: 3,
        caseColor: 'white',
        pawn_spec: 0,
    },
    truc: {
        pieceName: 'none',
        pieceColor: 'none',
        isAlive: 0,
        positionX: 5,
        positionY: 3,
        caseColor: 'black',
        pawn_spec: 0,
    },
    truc: {
        pieceName: 'none',
        pieceColor: 'none',
        isAlive: 0,
        positionX: 6,
        positionY: 3,
        caseColor: 'white',
        pawn_spec: 0,
    },
    truc: {
        pieceName: 'none',
        pieceColor: 'none',
        isAlive: 0,
        positionX: 7,
        positionY: 3,
        caseColor: 'black',
        pawn_spec: 0,
    },
    truc: {
        pieceName: 'none',
        pieceColor: 'none',
        isAlive: 0,
        positionX: 8,
        positionY: 3,
        caseColor: 'white',
        pawn_spec: 0,
    },
    truc: {
        pieceName: 'pawn_01',
        pieceColor: 'white',
        isAlive: 1,
        positionX: 1,
        positionY: 2,
        caseColor: 'white',
        pawn_spec: 0,
    },
    truc: {
        pieceName: 'pawn_02',
        pieceColor: 'white',
        isAlive: 1,
        positionX: 2,
        positionY: 2,
        caseColor: 'black',
        pawn_spec: 0,
    },
    truc: {
        pieceName: 'pawn_03',
        pieceColor: 'white',
        isAlive: 1,
        positionX: 3,
        positionY: 2,
        caseColor: 'white',
        pawn_spec: 0,
    },
    truc: {
        pieceName: 'pawn_04',
        pieceColor: 'white',
        isAlive: 1,
        positionX: 4,
        positionY: 2,
        caseColor: 'black',
        pawn_spec: 0,
    },
    truc: {
        pieceName: 'pawn_05',
        pieceColor: 'white',
        isAlive: 1,
        positionX: 5,
        positionY: 2,
        caseColor: 'white',
        pawn_spec: 0,
    },
    truc: {
        pieceName: 'pawn_06',
        pieceColor: 'white',
        isAlive: 1,
        positionX: 6,
        positionY: 2,
        caseColor: 'black',
        pawn_spec: 0,
    },
    truc: {
        pieceName: 'pawn_07',
        pieceColor: 'white',
        isAlive: 1,
        positionX: 7,
        positionY: 2,
        caseColor: 'white',
        pawn_spec: 0,
    },
    truc: {
        pieceName: 'pawn_08',
        pieceColor: 'white',
        isAlive: 1,
        positionX: 8,
        positionY: 2,
        caseColor: 'black',
        pawn_spec: 0,
    },
    truc: {
        pieceName: 'rook_01',
        pieceColor: 'white',
        isAlive: 1,
        positionX: 1,
        positionY: 1,
        caseColor: 'black',
        pawn_spec: 0,
    },
    truc: {
        pieceName: 'knight_01',
        pieceColor: 'white',
        isAlive: 1,
        positionX: 2,
        positionY: 1,
        caseColor: 'white',
        pawn_spec: 0,
    },
    truc: {
        pieceName: 'bishop_01',
        pieceColor: 'white',
        isAlive: 1,
        positionX: 3,
        positionY: 1,
        caseColor: 'black',
        pawn_spec: 0,
    },
    truc: {
        pieceName: 'queen_01',
        pieceColor: 'white',
        isAlive: 1,
        positionX: 4,
        positionY: 1,
        caseColor: 'white',
        pawn_spec: 0,
    },
    truc: {
        pieceName: 'king_01',
        pieceColor: 'white',
        isAlive: 1,
        positionX: 5,
        positionY: 1,
        caseColor: 'black',
        pawn_spec: 0,
    },
    truc: {
        pieceName: 'bishop_02',
        pieceColor: 'white',
        isAlive: 1,
        positionX: 6,
        positionY: 1,
        caseColor: 'white',
        pawn_spec: 0,
    },
    truc: {
        pieceName: 'knight_02',
        pieceColor: 'white',
        isAlive: 1,
        positionX: 7,
        positionY: 1,
        caseColor: 'black',
        pawn_spec: 0,
    },
    truc: {
        pieceName: 'rook_02',
        pieceColor: 'white',
        isAlive: 1,
        positionX: 8,
        positionY: 1,
        caseColor: 'white',
        pawn_spec: 0,
    },
}